const gameState = {
  WAITING_FOR_GAME_START: "WAITING_FOR_GAME_START",
  GAME_STARTED: "GAME_STARTED",
  HAND_ENDED: "HAND_ENDED",
  READY_TO_START_HAND: "READY_TO_START_HAND",
  HAND_IN_PROGRESS: "HAND_IN_PROGRESS",
  WAITING_FOR_PLAYER: "WAITING_FOR_PLAYER",
};

module.exports = gameState;